/*eslint no-console: ["error", { allow: ["error"] }]*/
const envVars = {
    API_DOMAIN: 'http://localhost:8080',
    GOOGLE_VERIFICATION_DOMAIN: 'http://localhost:3000',
    STRIPE_PUBLISHABLE_KEY: 'pk_test_TaSu0cLjeUyAGue34LrGlK3m',
    GOOGLE_REDIRECT_URI: 'http://localhost:4000/integration',
    GOOGLE_CLIENT_ID: '',
    GOOGLE_CLIENT_SECRET: '',
    PUBLIC_SITE_DOMAIN: 'http://local.mobileaction.co'
  };

if (process.env.NODE_ENV == 'production') {

  // Fetch variables from environment variables
  for( let key in constants){


    if(process.env[key])
      console.error(`Cannot find ${key} in environment variables`);
    constants[key] = process.env[key];
  }
}

const constants = {
  url: {
    SELF_DOMAIN: '/',
    API_DOMAIN: envVars.API_DOMAIN,
    PUBLIC_SITE_DOMAIN: envVars.API_DOMAIN
  },
  configVars:{
    stripePublishableKey: envVars.STRIPE_PUBLISHABLE_KEY,
    googleClientID: envVars.GOOGLE_CLIENT_ID,
    googleClientSecret: envVars.GOOGLE_CLIENT_SECRET,
    googleRedirectURI: envVars.GOOGLE_REDIRECT_URI,
    googleVerification: envVars.GOOGLE_VERIFICATION_DOMAIN
  }
};

constants.url.api = {
  userInfo: envVars.API_DOMAIN+ '/user/info',
  login: envVars.API_DOMAIN+ '/login',
  googleLogin: envVars.API_DOMAIN+ '/google-login',
  logout: envVars.API_DOMAIN+ '/logout',
  facebookLogin: envVars.API_DOMAIN+ '/facebook-login',
  validateAccountSignup: envVars.API_DOMAIN+ '/account/validate',
  createAccount: envVars.API_DOMAIN+ '/account',
  createAccountWithGoogle: envVars.API_DOMAIN+ '/account-with-google',
  createAccountWithFacebook: envVars.API_DOMAIN+ '/account-with-facebook',
  addAppToAccount: envVars.API_DOMAIN+ '/account/${accountId}/app',
  removeAppFromAccount: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/remove',
  trackCompetitor: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/competitor',
  untrackCompetitor: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/competitor',
  recommendedActionAnalytics: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/recommendedActionAnalytics',
  recommendedActions: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/recommended-actions?actions=${actions}',
  markRecommendedAction: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/markrecommendedaction',
  addStoreCredential: envVars.API_DOMAIN+ '/account/${accountId}/store-credential',
  visibilityScore: envVars.API_DOMAIN+ '/store/${storeName}/${country}/app/${trackId}/visibility-score',
  possibleCompetitors: envVars.API_DOMAIN+ '/store/${storeName}/${country}/app/${trackId}/competitors',
  appInfo: envVars.API_DOMAIN+ '/v3/store/${storeName}/app/${trackId}/${region}/app-info',
  keywordHistory: envVars.API_DOMAIN+ '/store/${storeName}/app/${appId}/${region}/${device}/${keyword}/keyword-history/${startDate}/${endDate}',
  visibilityScoreHistory: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/${region}/${device}/visibility-score-history/${startDate}/${endDate}',
  dataHistory: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/${region}/${device}/data-history/${context}/${startDate}/${endDate}',
  conversionRate: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/conversion-rate/${startDate}/${endDate}',
  retentionHistory: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/retention-history/${startDate}/${endDate}',
  retentionHistoryData: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/retention-history-data/${startDate}/${endDate}',
  peakTime: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/peak-time/${countryCode}',
  localizationAdvance: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/localization-advance',
  localization: envVars.API_DOMAIN+ '/store/${storeName}/app/${trackId}/localization',
  addKeywords: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/keywords',
  deleteKeyword: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/keywords',
  deleteMultipleKeywords: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/multiple-keywords',
  deleteAllKeywords: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/remove-all-keywords',
  appKeywordList: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/${device}/keywords',
  setKeywordColor: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/${keyword}/color/${color}',
  unsetKeywordColor: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/${keyword}/uncolor',
  pinKeyword: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/${keyword}/pin',
  unpinKeyword: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/${keyword}/unpin',
  setKeywordNote: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/${keyword}/note/${note}',
  changePassword: envVars.API_DOMAIN+ '/account/change-password',
  storeAccountList: envVars.API_DOMAIN+ '/account/${accountId}/store-account-list',
  deleteStoreAccount: envVars.API_DOMAIN+ '/account/${accountId}/store-account/${storeAcccountId}',
  getMembers: envVars.API_DOMAIN+ '/account/${accountId}/members',
  getPaymentInfo: envVars.API_DOMAIN+ '/account/${accountId}/payment-info',
  inviteMember: envVars.API_DOMAIN+ '/account/${accountId}/invite-member',
  inviteMembers: envVars.API_DOMAIN+ '/account/${accountId}/invite-members',
  changeAdmin: envVars.API_DOMAIN+ '/account/${accountId}/change-admin/${id}',
  reinvite: envVars.API_DOMAIN+ '/account/${accountId}/reinvite-member/${id}',
  deleteMember: envVars.API_DOMAIN+ '/account/${accouentId}/delete-user/${id}',
  addCreditCard: envVars.API_DOMAIN+ '/account/${accountId}/add-credit-card',
  stripePlan: envVars.API_DOMAIN+ '/account/${accountId}/stripe-plan?planName=${planName}&planPeriod=${planPeriod}',
  applyCoupon: envVars.API_DOMAIN+ '/account/${accountId}/apply-coupon?couponId=${couponId}',
  subscribe: envVars.API_DOMAIN+ '/account/${accountId}/subscribe',
  subscribeExistingCustomer: envVars.API_DOMAIN+ '/account/${accountId}/subscribe-existing-customer',
  keywordCountByCountry: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/keyword-count-by-country',
  keywordSpot: envVars.API_DOMAIN+ '/account/${accountId}/app/${appId}/${region}/keyword-spot',
  announcement: envVars.API_DOMAIN+ '/account/${accountId}/announcement',
  invoiceDetail: envVars.API_DOMAIN+ '/account/${accountId}/invoice-detail/${invoiceId}',
  updateNotificationPreferences: envVars.API_DOMAIN+ '/user/update-notification-prerferences',
  notificationPreferences: envVars.API_DOMAIN+ '/user/notification-prerferences',
  googleAuthSave: envVars.API_DOMAIN+ "account/${accountId}/google-access",
  facebookAuthSave: envVars.API_DOMAIN+ "account/${accountId}/facebook-access",
  sendGPVerificationEmail: envVars.API_DOMAIN+ "account/${accountId}/send-gp-verification-email",
  verifyGPEmail: envVars.API_DOMAIN+ "account/${accountId}/verify-gp-email",
  markNotificationsAsRead: envVars.API_DOMAIN+ "account/${accountId}/mark-notifications-as-read",
  cancelSubscription: envVars.API_DOMAIN+ "account/${accountId}/cancel-subscription",
  actions: envVars.API_DOMAIN+ "account/${accountId}/app/${appId}/${countryCode}/actions?group=${group}&name=${name}",
  appSearch: '/v3/store/${storeName}/app/search?region=${region}&query=${query}',
  keywordAnalysis: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/keyword-analysis?apiKey=${apiKey}',
  keywordsPlain: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/keywords-plain?apiKey=${apiKey}',
  keywordRecommendation: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/keyword-recommendation?apiKey=${apiKey}',
  relativeKeywords: '/v3/relative-keywords/?keyword=${keyword}&region=${region}&apiKey=${apiKey}',
  relatedKeywords: '/v3/related-keywords/?keyword=${keyword}&region=${region}&apiKey=${apiKey}',
  trendingKeywords: '/v3/trending-keywords/?region=${region}&apiKey=${apiKey}',
  appRegions: '/v3/store/${storeName}/app/${trackId}/regions',
  appVersionHistory: '/v3/store/${storeName}/app/${trackId}/version-history',
  categoryRankings: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/category-rankings/${startDate}/${endDate}?apiKey=${apiKey}',
  categoryRankingsHourly: '/v3/store/app/${trackId}/${region}/${device}/category-rankings-hourly/${startDate}/${endDate}?apiKey=${apiKey}',
  reviewHistory: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/reviews/${startDate}/${endDate}?apiKey=${apiKey}',
  ratingHistory: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/ratings/${startDate}/${endDate}?apiKey=${apiKey}',
  reviewWordDensity: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/word-freq/${startDate}/${endDate}?apiKey=${apiKey}',
  topAppsForKeyword: '/v3/store/${storeName}/app/${trackId}/top-apps?region=${region}&device=${device}&keyword=${keyword}&apiKey=${apiKey}',
  downloadEstimation: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/download-estimation/${startDate}/${endDate}?apikey=${apikey}',
  downloadEstimationDummyData: '/staticdata/dummy_data_for_download_estimation_${region}_${version}.json',
  dummyDataForDataHistory: '/staticdata/dummy_data_for_data_history.json',
  revenueEstimation: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/revenue-estimation/${startDate}/${endDate}?apikey=${apikey}',
  dauEstimation: '/v3/store/${storeName}/app/${trackId}/${countryCode}/${device}/estimate-dau-daily/${startDate}/${endDate}?apikey=${apikey}',
  mauEstimation: '/v3/store/${storeName}/app/${trackId}/${countryCode}/${device}/estimate-mau-daily/${startDate}/${endDate}?apikey=${apikey}',
  topApps: '/v3/store/${storeName}/${region}/${device}/${category}/${listType}/top-apps/${date}',
  newApps: '/v3/store/${storeName}/${region}/${device}/${category}/${listType}/new-apps/${date}',
  publisher: '/v3/store/${storeName}/publisher/${name}',
  appsByDomain: '/v3/store/${storeName}/apps-by-domain/${domainName}?apiKey=${apiKey}',
  countrySummary: '/v3/store/${storeName}/country-summary/${trackId}/${region}/${startDate}/${endDate}?apikey=${apikey}',
  saveActionGoal: envVars.API_DOMAIN+ "account/${accountId}/app/${trackId}/action/save-goal",
  addSearchLog: envVars.API_DOMAIN+ "log/add-search-log",
  canSearchMore: envVars.API_DOMAIN+ "log/can-search-more",
  keywordIntelLog: envVars.API_DOMAIN+ "log/keyword-intel/{trackId}",
  addBucketListLog: envVars.API_DOMAIN+ "log/add-bucket-list-log",
  getClientIP: '/get-client-ip',
  audience: envVars.API_DOMAIN+ "account/${accountId}/audience",
  marketCouponCreate: envVars.API_DOMAIN+ "account/${accountId}/createMarketCoupon",
  competitorCouponCreate: envVars.API_DOMAIN+ "account/${accountId}/createCompetitorCoupon",
  categoryRankingSummary: '/v3/store/${storeName}/app/${trackId}/${device}/category-rankings-summary/${startDate}/${endDate}?apiKey=${apiKey}',
  markActionAsDone: envVars.API_DOMAIN+ "account/${accountId}/app/${appId}/action/${actionId}/mark-as-done",
  sendEmailVerificationCode: envVars.API_DOMAIN+ "account/send-verification-code",
  verifyEmail: envVars.API_DOMAIN+ "account/verify-email",
  applyReferrer: envVars.API_DOMAIN+ "account/${accountId}/apply-referrer-campaign",
  referrerList: envVars.API_DOMAIN+ "getReferrerList",
  keywordDownloads: '/v3/store/${storeName}/${trackId}/${countryCode}/keyword-dowloads?apiKey=${apiKey}',
  customAlerts: envVars.API_DOMAIN+ '/account/${accountId}/custom-alerts',
  addCustomAlert: envVars.API_DOMAIN+ '/account/${accountId}/save-custom-alert',
  getCustomAlertLimitUsage: envVars.API_DOMAIN+ '/account/${accountId}/custom-aler-limit-usage',
  deleteCustomAlert: envVars.API_DOMAIN+ '/account/${accountId}/delete-notification/${id}',
  publisherLeaderboard: '/v3/store/${storeName}/publisher-leaderboard/${start}/${pageSize}/?categoryId=${categoryId}&apiKey=${apiKey}',
  keywordInfo: '/v3/store/${storeName}/app/${trackId}/${region}/${device}/keyword-info/${keyword}',
  saveIntelligenceApp: envVars.API_DOMAIN+ "account/${accountId}/save-intelligence-app/${trackId}/${storeName}/${plan}",
  deleteIntelligenceApp: envVars.API_DOMAIN+ "account/${accountId}/delete-intelligence-app/${trackId}/${plan}",
  searchAdsDashboardPage: "/searchads",
  searchAdsConnect: envVars.API_DOMAIN+ "search-ads/account/connect",
  searchAdsReportCampaigns: envVars.API_DOMAIN+ "search-ads/reports/campaigns?start=${startDate}&end=${endDate}",
  searchAdsCampReportAdgroups: envVars.API_DOMAIN+ "search-ads/reports/campaigns/${campId}/adgroups?start=${startDate}&end=${endDate}",
  searchAdsCampReportKeywords: envVars.API_DOMAIN+ "search-ads/reports/campaigns/${campId}/keywords?start=${startDate}&end=${endDate}",
  searchAdsCampReportSearchTerms: envVars.API_DOMAIN+ "search-ads/reports/campaigns/${campId}/searchterms?start=${startDate}&end=${endDate}",
  keywordIntelligenceCredits: envVars.API_DOMAIN+ "account/${accountId}/keyword-intelligence-free-credits?apiKey=${apiKey}",
  marketIntelligenceCredits: envVars.API_DOMAIN+ "account/${accountId}/market-intelligence-free-credits?apiKey=${apiKey}"
};

export default constants;
