export default {
  userInfo: 'user/info',
  login: 'login',
  googleLogin: 'google-login',
  logout: 'logout',
  facebookLogin: 'facebook-login',
  validateAccountSignup: 'account/validate',

  createAccount: 'account',
  createAccountWithGoogle: 'account-with-google',
  createAccountWithFacebook: 'account-with-facebook',

  addAppToAccount: 'account/${accountId}/app',
  removeAppFromAccount: 'account/${accountId}/app/${appId}/remove',

  trackCompetitor: 'account/${accountId}/app/${appId}/competitor',
  untrackCompetitor: 'account/${accountId}/app/${appId}/competitor',

  recommendedActionAnalytics: 'account/${accountId}/app/${appId}/recommendedActionAnalytics',
  recommendedActions: 'account/${accountId}/app/${appId}/${region}/recommended-actions?actions=${actions}',
  saveActionGoal: "account/${accountId}/app/${trackId}/action/save-goal",
  markActionAsDone: "account/${accountId}/app/${appId}/action/${actionId}/mark-as-done",
  markRecommendedAction: 'account/${accountId}/app/${appId}/markrecommendedaction',
  actions: "account/${accountId}/app/${appId}/${countryCode}/actions?group=${group}&name=${name}",
  recActionWithValue: "recActions/app/${trackId}/action/${actionName}/${countryCode}",

  addStoreCredential: 'account/${accountId}/store-credential',
  visibilityScore: 'store/${storeName}/${country}/app/${trackId}/visibility-score',
  possibleCompetitors: 'store/${storeName}/${country}/app/${trackId}/competitors',
  appInfo: 'v3/store/${storeName}/app/${trackId}/${region}/app-info',
  keywordHistory: 'store/${storeName}/app/${appId}/${region}/${device}/${keyword}/keyword-history/${startDate}/${endDate}',
  visibilityScoreHistory: 'store/${storeName}/app/${trackId}/${region}/${device}/visibility-score-history/${startDate}/${endDate}',
  dataHistory: 'store/${storeName}/app/${trackId}/${region}/${device}/data-history/${context}/${startDate}/${endDate}',
  conversionRate: 'store/${storeName}/app/${trackId}/conversion-rate/${startDate}/${endDate}',
  retentionHistory: 'store/${storeName}/app/${trackId}/retention-history/${startDate}/${endDate}',
  retentionHistoryData: 'store/${storeName}/app/${trackId}/retention-history-data/${startDate}/${endDate}',
  peakTime: 'store/${storeName}/app/${trackId}/peak-time/${countryCode}',
  localizationAdvance: 'store/${storeName}/app/${trackId}/localization-advance',
  localization: 'store/${storeName}/app/${trackId}/localization',
  addKeywords: 'account/${accountId}/app/${appId}/${region}/keywords',
  deleteKeyword: 'account/${accountId}/app/${appId}/${region}/keywords',
  deleteMultipleKeywords: 'account/${accountId}/app/${appId}/${region}/multiple-keywords',
  deleteAllKeywords: 'account/${accountId}/app/${appId}/${region}/remove-all-keywords',
  appKeywordList: 'account/${accountId}/app/${appId}/${region}/${device}/keywords',
  setKeywordColor: 'account/${accountId}/app/${appId}/${region}/${keyword}/color/${color}',
  unsetKeywordColor: 'account/${accountId}/app/${appId}/${region}/${keyword}/uncolor',
  pinKeyword: 'account/${accountId}/app/${appId}/${region}/${keyword}/pin',
  unpinKeyword: 'account/${accountId}/app/${appId}/${region}/${keyword}/unpin',
  setKeywordNote: 'account/${accountId}/app/${appId}/${region}/${keyword}/note/${note}',
  changePassword: 'account/change-password',
  storeAccountList: 'account/${accountId}/store-account-list',
  deleteStoreAccount: 'account/${accountId}/store-account/${storeAcccountId}',
  getMembers: 'account/${accountId}/members',
  getPaymentInfo: 'account/${accountId}/payment-info',
  inviteMember: 'account/${accountId}/invite-member',
  inviteMembers: 'account/${accountId}/invite-members',
  changeAdmin: 'account/${accountId}/change-admin/${id}',
  reinvite: 'account/${accountId}/reinvite-member/${id}',
  deleteMember: 'account/${accouentId}/delete-user/${id}',
  addCreditCard: 'account/${accountId}/add-credit-card',
  stripePlan: 'account/${accountId}/stripe-plan?planName=${planName}&planPeriod=${planPeriod}',
  applyCoupon: 'account/${accountId}/apply-coupon?couponId=${couponId}',
  subscribe: 'account/${accountId}/subscribe',
  subscribeExistingCustomer: 'account/${accountId}/subscribe-existing-customer',
  keywordCountByCountry: 'account/${accountId}/app/${appId}/keyword-count-by-country',
  keywordSpot: 'account/${accountId}/app/${appId}/${region}/keyword-spot',
  announcement: 'account/${accountId}/announcement',
  invoiceDetail: 'account/${accountId}/invoice-detail/${invoiceId}',
  updateNotificationPreferences: 'user/update-notification-prerferences',
  notificationPreferences: 'user/notification-prerferences',
  googleAuthSave: "account/${accountId}/google-access",
  facebookAuthSave: "account/${accountId}/facebook-access",
  sendGPVerificationEmail: "account/${accountId}/send-gp-verification-email",
  verifyGPEmail: "account/${accountId}/verify-gp-email",
  markNotificationsAsRead: "account/${accountId}/mark-notifications-as-read",
  cancelSubscription: "account/${accountId}/cancel-subscription",

  addSearchLog: "log/add-search-log",
  canSearchMore: "log/can-search-more",
  keywordIntelLog: "log/keyword-intel/{trackId}",
  addBucketListLog: "log/add-bucket-list-log",

  audience: "account/${accountId}/audience",
  marketCouponCreate: "account/${accountId}/createMarketCoupon",
  competitorCouponCreate: "account/${accountId}/createCompetitorCoupon",

  sendEmailVerificationCode: "account/send-verification-code",
  verifyEmail: "account/verify-email",
  applyReferrer: "account/${accountId}/apply-referrer-campaign",
  referrerList: "getReferrerList",


  customAlerts: 'account/${accountId}/custom-alerts',
  addCustomAlert: 'account/${accountId}/save-custom-alert',
  getCustomAlertLimitUsage: 'account/${accountId}/custom-aler-limit-usage',
  deleteCustomAlert: 'account/${accountId}/delete-notification/${id}',



  saveIntelligenceApp: "account/${accountId}/save-intelligence-app/${trackId}/${storeName}/${plan}",
  deleteIntelligenceApp: "account/${accountId}/delete-intelligence-app/${trackId}/${plan}",

  searchAdsConnect: "search-ads/account/connect",
  searchAdsReportCampaigns: "search-ads/reports/campaigns?start=${startDate}&end=${endDate}",
  searchAdsCampReportAdgroups: "search-ads/reports/campaigns/${campId}/adgroups?start=${startDate}&end=${endDate}",
  searchAdsCampReportKeywords: "search-ads/reports/campaigns/${campId}/keywords?start=${startDate}&end=${endDate}",
  searchAdsCampReportSearchTerms: "search-ads/reports/campaigns/${campId}/searchterms?start=${startDate}&end=${endDate}",

  keywordIntelligenceCredits: "account/${accountId}/keyword-intelligence-free-credits?apiKey=${apiKey}",
  marketIntelligenceCredits: "account/${accountId}/market-intelligence-free-credits?apiKey=${apiKey}"
};
